# app/config.py

import os, re 
import json
import logging
from pathlib import Path
from typing import List, Set, Tuple, Dict, Any

from azure.storage.blob import BlobServiceClient

# ============= FIELD CONSTANTS =============
UID         = "uid"
UPDATE      = "updatedAt"
TITLE       = "title_fr"
DESC        = "description_fr"
LONG_DESC   = "longdescription_fr"
LOC_NAME    = "location_name"
LOC_DEPT    = "location_department"
LOC_CITY    = "location_city"
LOC_REGION  = "location_region"
LOC_ADDRESS = "location_address"
CONDITIONS  = "conditions_fr"
URL         = "canonicalurl"
LOC_COORD   = "location_coordinates"
LOC_LAT     = "location_lat"
LOC_LON     = "location_lon"
TIMINGS     = "timings"
FIRST_DATE  = "first_date"

# Fields concatenated for embedding
VECTORIZED_FIELDS = [
    TITLE, DESC, LONG_DESC, CONDITIONS,
    LOC_NAME, LOC_CITY, LOC_ADDRESS, LOC_DEPT, LOC_REGION
]

# Fields kept as metadata for filtering (Azure AI Search / OData)
METADATA_FIELDS = [
    UID, UPDATE, TITLE, DESC, LONG_DESC, LOC_NAME, LOC_DEPT,
    LOC_CITY, LOC_REGION, LOC_ADDRESS, CONDITIONS, URL, TIMINGS, LOC_COORD
]


# ============= LOGGING SETUP =============

def setup_logging() -> None:
    """
    Initializes global logging configuration using environment variables.
    The 'force=True' parameter ensures this config overrides any default
    settings from third-party libraries.
    """
    log_level_str = os.getenv("LOG_LEVEL", "INFO").upper()
    level = getattr(logging, log_level_str, logging.INFO)
    logging.basicConfig(
        level=level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        force=True
    )
    logging.getLogger("app.config").info(
        f"Logging system initialized at {log_level_str} level."
    )

setup_logging()
logger = logging.getLogger(__name__)


# ============= STRING NORMALIZATION =============

def normalize_location_name(text: str) -> str:
    """
    Normalizes a string for OData filtering and comparison:
    lowercases, strips, removes accents, replaces hyphens/slashes with spaces.

    Args:
        text (str): Input string.

    Returns:
        str: Normalized string.
    """
    if not text:
        return ""
    s = text.strip().lower()
    accents = {
        'a': ['à', 'ã', 'á', 'â'],
        'e': ['é', 'è', 'ê', 'ë'],
        'i': ['î', 'ï'],
        'u': ['ù', 'ü', 'û'],
        'o': ['ô', 'ö'],
        ' ': ['-', '/']
    }
    for char, chars in accents.items():
        for c in chars:
            s = s.replace(c, char)
    text = re.sub(r'\bste\b', 'sainte', s)
    text = re.sub(r'\bst\b',  'saint',  s)

    return text


# ============= GEOGRAPHIC REFERENCE DATA =============

_location_cache: dict = {"cities": [], "depts": [], "loaded": False}


def get_cached_locations() -> Tuple[List[str], List[str]]:
    """
    Returns cached cities and departments.
    Falls back to live fetch if cache is not yet loaded.

    Returns:
        Tuple[List[str], List[str]]: Sorted lists of cities and departments.
    """
    if not _location_cache["loaded"]:
        warm_location_cache()
    return _location_cache["cities"], _location_cache["depts"]


def warm_location_cache() -> None:
    """
    Forces a fresh load of geographic data into the module-level cache.
    Called once at app startup via on_app_startup in ui.py.
    """
    cities, depts = get_unique_locations()
    _location_cache["cities"] = cities
    _location_cache["depts"]  =  clean_departments(depts)
    _location_cache["loaded"] = True
    logger.info(
        f"Location cache warmed: {len(cities)} cities, {len(depts)} departments."
    )

def clean_departments(depts: List[str]) -> List[str]:
    """
    Cleans the department list by:
      - Removing entries that contain digits (e.g. '11 - Aude', '75001')
      - Deduplicating case-insensitively (keeps the first occurrence)
      - Capitalizing each entry (e.g. 'creuse' → 'Creuse')

    Args:
        depts (List[str]): Raw department list.

    Returns:
        List[str]: Cleaned, deduplicated and capitalized department list.
    """
    import re
    seen = set()
    result = []
    for d in depts:
        if re.search(r'\d', d):
            continue
        key = normalize_location_name(d)
        if key in seen:
            continue
        seen.add(key)
        result.append(d.strip().title())
    return sorted(result)

def get_unique_locations() -> Tuple[List[str], List[str]]:
    """
    Retrieves unique cities and departments.

    Priority:
        1. gold/locations.json (generated by ingestion pipeline) — fastest
        2. Silver Blob Storage — fallback if locations.json missing
        3. Local data/gold/locations.json — local dev fallback

    Returns:
        Tuple[List[str], List[str]]: (cities, departments) sorted.
    """
    env = os.getenv("ENV", "LOCAL").upper()

    if env == "AZURE":
        # 1. Try gold/locations.json first
        result = _get_locations_from_gold_blob()
        if result[0]:
            return result
        # 2. Fallback to Silver
        logger.warning("locations.json not found in gold, falling back to Silver.")
        return _get_locations_from_silver()
    else:
        # Local: try data/gold/locations.json first
        result = _get_locations_from_gold_local()
        if result[0]:
            return result
        return _get_locations_from_silver()


def _get_locations_from_gold_blob() -> Tuple[List[str], List[str]]:
    """
    Reads gold/locations.json from Azure Blob Storage.
    This file is generated and updated by the ingestion pipeline.

    Returns:
        Tuple[List[str], List[str]]: (cities, departments) or ([], []) if not found.
    """
    try:
        conn_str = os.getenv("AZURE_STORAGE_CONNECTION_STRING", "")
        if not conn_str:
            return [], []

        client      = BlobServiceClient.from_connection_string(conn_str)
        blob_client = client.get_blob_client(container="gold", blob="locations.json")

        if not blob_client.exists():
            return [], []

        data = json.loads(blob_client.download_blob().readall().decode('utf-8'))
        cities = data.get("cities", [])
        depts  = data.get("departments", [])

        logger.info(
            f"Locations loaded from gold/locations.json: "
            f"{len(cities)} cities, {len(depts)} departments."
        )
        return sorted(cities, key=lambda x: x.lower()), \
               sorted(depts,  key=lambda x: x.lower())

    except Exception as e:
        logger.warning(f"Failed to read gold/locations.json from Blob: {e}")
        return [], []


def _get_locations_from_gold_local() -> Tuple[List[str], List[str]]:
    """
    Reads data/gold/locations.json from the local filesystem.
    Used in local development mode.

    Returns:
        Tuple[List[str], List[str]]: (cities, departments) or ([], []) if not found.
    """
    local_path = Path("data/gold/locations.json")
    if not local_path.exists():
        return [], []
    try:
        with open(local_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        cities = data.get("cities", [])
        depts  = data.get("departments", [])
        logger.info(
            f"Locations loaded from local gold/locations.json: "
            f"{len(cities)} cities, {len(depts)} departments."
        )
        return sorted(cities, key=lambda x: x.lower()), \
               sorted(depts,  key=lambda x: x.lower())
    except Exception as e:
        logger.warning(f"Failed to read local locations.json: {e}")
        return [], []


def _get_locations_from_silver() -> Tuple[List[str], List[str]]:
    """
    Fallback: reads unique cities and departments from the last 10 Silver files.
    Used when gold/locations.json is not available.

    Returns:
        Tuple[List[str], List[str]]: (cities, departments) sorted.
    """
    env = os.getenv("ENV", "LOCAL").upper()
    cities: Set[str] = set()
    depts:  Set[str] = set()

    container_client = None
    if env == "AZURE":
        conn_str = os.getenv("AZURE_STORAGE_CONNECTION_STRING")
        if not conn_str:
            return [], []
        client = BlobServiceClient.from_connection_string(conn_str)
        container_client = client.get_container_client("silver")
        blobs = sorted(
            container_client.list_blobs(),
            key=lambda x: x.name,
            reverse=True
        )[:10]
    else:
        silver_path = Path("data/silver")
        blobs = sorted(silver_path.glob("events_*.json*"), reverse=True)[:10]

    for b in blobs:
        try:
            if env == "AZURE":
                content = container_client.get_blob_client(b.name).download_blob().readall().decode('utf-8')  # type: ignore
            else:
                with open(b, 'r', encoding='utf-8') as f:  # type: ignore
                    content = f.read()

            try:
                data = json.loads(content)
            except json.JSONDecodeError:
                data = content.splitlines()

            if isinstance(data, str):
                data = data.splitlines()
            elif not isinstance(data, list):
                data = [data]

            for item in data:
                event = item
                if isinstance(item, str):
                    try:
                        event = json.loads(item)
                    except Exception:
                        continue
                if isinstance(event, dict):
                    city = event.get("location_city")
                    dept = event.get("location_department")
                    if city:
                        cities.add(city)
                    if dept:
                        depts.add(dept)
        except Exception as e:
            logger.warning(f"Failed to process blob {b}: {e}")
            continue

    return sorted(list(cities), key=lambda x: x.lower()), \
           sorted(list(depts),  key=lambda x: x.lower())